import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Resource } from "sst";

console.log("Resource.SOME_SECRET", Resource.SomeSecret.value);
console.log("process.env.SOME_SECRET", process.env.SOME_SECRET);

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
